using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TpvlDataAnalyzer.Model
{
    public enum PlayerSortCriterion
    {
        Score,
        ServesCompleteRate,
        ServesAttemptRate,
        ServesErrorRate,
        ServesTotal,
        SpikesCompleteRate,
        SpikesAttemptRate,
        SpikesErrorRate,
        SpikesTotal,
        SetsCompleteRate,
        SetsAttemptRate,
        SetsErrorRate,
        SetsTotal,
        BlocksCompleteRate,
        BlocksAttemptRate,
        BlocksErrorRate,
        BlocksTotal,
        PassesCompleteRate,
        PassesAttemptRate,
        PassesErrorRate,
        PassesTotal,
        DefensesCompleteRate,
        DefensesAttemptRate,
        DefensesErrorRate,
        DefensesTotal,
        ServesCompleteCount,
        ServesAttemptCount,
        ServesErrorCount,
        SpikesCompleteCount,
        SpikesAttemptCount,
        SpikesErrorCount,
        SetsCompleteCount,
        SetsAttemptCount,
        SetsErrorCount,
        BlocksCompleteCount,
        BlocksAttemptCount,
        BlocksErrorCount,
        PassesCompleteCount,
        PassesAttemptCount,
        PassesErrorCount,
        DefensesCompleteCount,
        DefensesAttemptCount,
        DefensesErrorCount,
        AvgScorePerRound,
        AvgSpikesPerRound,
        CompleteCount,
        ErrorCount,
        AttackTotal,
        AttackErrorCount,
        AttackErrorRate,
        AttackCompleteCount,
        AttackCompleteRate,
        AttackAttemptCount,
        AttackAttemptRate,
        ResistanceTotal,
        ResistanceErrorCount,
        ResistanceErrorRate,
        ResistanceCompleteCount,
        ResistanceCompleteRate,
        ResistanceAttemptCount,
        ResistanceAttemptRate,
    }
}