namespace TpvlDataAnalyzer.Model{ 

    public class RefereePage
    {
        public string title_page_1 { get; set; }
        public string order_desc { get; set; }
        public string order_asc { get; set; }
        public string register { get; set; }
        public string scroll_down_tips { get; set; }
        public string next { get; set; }
        public string back { get; set; }
        public string cost_breakdown { get; set; }
        public string registration_fee { get; set; }
        public string name { get; set; }
        public string date_of_birth { get; set; }
        public string contact_phone_numbers { get; set; }
        public string registration_session { get; set; }
        public string time { get; set; }
        public string payment { get; set; }
        public string payment_method { get; set; }
        public string bank_transfer { get; set; }
        public string third_party_payment { get; set; }
        public string payment_bank_code { get; set; }
        public string payment_account { get; set; }
        public string account_last_digit { get; set; }
        public string please_enter_account { get; set; }
        public string discription_bank_account { get; set; }
        public string discription_third_party { get; set; }
        public string discription_third_party_1 { get; set; }
        public string copy_account { get; set; }
        public string cancel_button { get; set; }
        public string confirm_button { get; set; }
        public string payment_information { get; set; }
        public RegisterSuccess RegisterSuccess { get; set; }
        public string personal_information { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public string gender_male { get; set; }
        public string gender_female { get; set; }
        public string upload_file { get; set; }
        public string attach_desc1 { get; set; }
        public string attach_desc2 { get; set; }
        public string place_holder { get; set; }
        public string residential_address { get; set; }
        public string mailing_address { get; set; }
        public string residential_street { get; set; }
        public string mailing_street { get; set; }
        public string same_residential_address { get; set; }
        public string upload_id_document { get; set; }
        public string id_card { get; set; }
        public string driver_licence { get; set; }
        public string passport { get; set; }
        public string id_number { get; set; }
        public string issue_date { get; set; }
        public string expiration_date { get; set; }
        public string landline { get; set; }
        public string mobile { get; set; }
        public string please_enter_your_phone { get; set; }
        public string please_enter_your_email { get; set; }
        public string current_occupation { get; set; }
        public string department { get; set; }
        public string please_enter_complete { get; set; }
        public string workplace_address { get; set; }
        public string position { get; set; }
        public string job_title { get; set; }
        public string institution { get; set; }
        public string occupation_description { get; set; }
        public string referee_license { get; set; }
        public string experience_various_competitions { get; set; }
        public string add_new_button { get; set; }
        public string cup_competitions_name { get; set; }
        public string delete_button { get; set; }
        public string upload_certificate { get; set; }
        public string document_certificate { get; set; }
        public string document_certificate_1 { get; set; }
        public string volleyball_experience { get; set; }
        public string up_500_characters { get; set; }
        public string registration_information_page_title { get; set; }
        public string registration_information { get; set; }
        public string emergency_contact { get; set; }
        public string relation { get; set; }
        public string agree_allow_description_1 { get; set; }
        public string agree_allow_description_2 { get; set; }
        public string agree_allow_description_3 { get; set; }
        public string have_read { get; set; }
        public string submit_button { get; set; }
        public string all_fields_required { get; set; }
        public string chinese { get; set; }
        public string english { get; set; }
        public string institution_yes_no { get; set; }
        public string dropdown_label { get; set; }
        public string grade_a { get; set; }
        public string grade_b { get; set; }
        public string grade_c { get; set; }
        public string experience { get; set; }
        public string en_roll { get; set; }
        public string information_chinese_1 { get; set; }
        public string information_chinese_2 { get; set; }
        public string information_chinese_3 { get; set; }
        public string spouse { get; set; }
        public string parents { get; set; }
        public string siblings { get; set; }
        public string relatives { get; set; }
        public string friends { get; set; }
        public string others { get; set; }
        public string login_or { get; set; }
        public string placeholder_emergencty_contact { get; set; }
        public string account_last_digit_error { get; set; }
        public string upload_certificate_photo_error { get; set; }
        public string upload_portrait_photo_error { get; set; }
        public string first_name_required { get; set; }
        public string last_name_required { get; set; }
        public string birthdate_required { get; set; }
        public string portrait_photo_required { get; set; }
        public string residential_street_required { get; set; }
        public string mailing_street_required { get; set; }
        public string id_number_required { get; set; }
        public string phone_number_required { get; set; }
        public string email_required { get; set; }
        public string department_required { get; set; }
        public string workplace_address_required { get; set; }
        public string job_title_required { get; set; }
        public string institution_required { get; set; }
        public string cup_competitions_name_required { get; set; }
        public Grade Grade { get; set; }
        public string certificate_required { get; set; }
        public string volleyball_experience_required { get; set; }
        public string volleyball_experience_max_length { get; set; }
        public Emergency Emergency { get; set; }
        public string phone_number_invalid { get; set; }
        public string email_invalid { get; set; }
        public string select_two_boxes { get; set; }
        public string birthdate_invalid { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string city_required { get; set; }
        public string district_required { get; set; }
        public string mailing_city_required { get; set; }
        public string mailing_district_required { get; set; }
        public string email_address { get; set; }
        public string company_address { get; set; }
        public string referee_qualification_certificate { get; set; }
        public string emer_contact_label_name { get; set; }
        public Note note { get; set; }
    }

}